### ISSUE TITLE
Picked colors are wrong

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/deepin-picker#1]
HOW TO REPRODUCE:
1. Using Deepin Picker, pick any color.
2. Paste the result somewhere.
3. Take a screenshot of the same color.
4. Using the app GIMP, pick the color and see its code.

RESULTS:
Colors are different.

**Comment by manateelazycat** [comment]
Patch has fixed https://github.com/linuxdeepin/deepin-picker/commit/ecf9f453c55a7f413d22d01f4b769607391eb1cd

Welcome to re-open this issue if you still have problem.

**Comment by es20490446e** [comment]
Thank you.
