### ISSUE TITLE
Black color always picked

### ISSUE THREAD

**Issue by visionmax** [linuxdeepin/deepin-picker#6]
Just installed it, and when I run the prograrm, black circle with white square in the center appears. I assume black circle is supposed to show enlarge details around cursor, but wherever I move it on my desktop, it is always black. Clicking with mouse creates notification saying black color was picked.

Photo of the issue:
[https://pasteboard.co/I6GMVV3.png](https://pasteboard.co/I6GMVV3.png)

Running on Ubuntu 18.04.2 LTS with latest updates.

**Comment by visionmax** [comment]
Update: it happens on **Wayland**, but works in normal mode. If support for Wayland is in plan, or not planned, would be good to put a notice about it somewhere visible.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
